<!DOCTYPE html>
<html lang="en">

<!-- index-11.html  11 Feb 2023 14:24:46 GMT -->

<head>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-KRL58MWH94"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KRL58MWH94');
</script>
	<title>Sponsorrs - Sponsorships for YouTube channels & Creators</title>

	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="https://sponsorrs.com">
	<meta name="description"
		content="Sponsorrs - Sponsorships for TouTube channels. Creators can apply for sponsorships created by brands. Easily accept payments in bank accounts.">

	<meta property="og:title" content="Sponsorrs - Sponsorships for YouTube channels & Creators">
	<meta property="og:description" content="Sponsorship platform for youtube channels">
	<meta property="og:image" content="assets/images/flaticon/sponsorrs_rect.png">
	<?php include_once("common_ui/dark-mode.php"); ?>

	<!-- Favicon -->
	<link rel="shortcut icon" href="assets/images/favicon.ico">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com/">
	<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&amp;family=Roboto:wght@400;500;700&amp;display=swap">

	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="assets/vendor/font-awesome/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor/bootstrap-icons/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor/tiny-slider/tiny-slider.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor/glightbox/css/glightbox.css">

	<!-- Theme CSS -->
	<link rel="stylesheet" type="text/css" href="assets/css/style.css">

</head>

<body>


	<!-- Header START -->
	<?php include_once('common_ui/header.php'); ?>
	<!-- Header END -->

	<!-- **************** MAIN CONTENT START **************** -->
	<main>

		<!-- ======================= Action box START -->
		<section class="py-0">
			<div class="container position-relative">
				<div class="row">
					<div class="col-12">
						<h3 class="fs-1 d-flex justify-content-center">Data Privacy Policy</h3>
						<h3>Data Privacy Policy</h3>
						<p>Effective date: 10th March 2023</p>
						<p>Sponsorrs ("us", "we", or "our") operates the Sponsorrs.com website (the
							"Service").</p>
						<p>This page informs you of our policies regarding the collection, use, and disclosure of
							personal data when you use our Service and the choices you have associated with that data.
						</p>
						<p>We use your data to provide and improve the Service. By using the Service, you agree to the
							collection and use of information in accordance with this policy. Unless otherwise defined
							in this Data Privacy Policy, terms used in this Data Privacy Policy have the same meanings
							as in our Terms and Conditions, accessible from Sponsorrs.com.</p>
						<h3>Definitions</h3>
						<ul>
							<li>Personal Data: Personal Data means data about a living individual who can be identified
								from those data (or from those and other information either in our possession or likely
								to come into our possession).</li>
							<li>Usage Data: Usage Data is data collected automatically either generated by the use of
								the Service or from the Service infrastructure itself (for example, the duration of a
								page visit).</li>
						</ul>
						<h3>Types of Data Collected</h3>
						<p><strong>Personal Data</strong></p>
						<p>While using our Service, we may ask you to provide us with certain personally identifiable
							information that can be used to contact or identify you ("Personal Data"). Personally
							identifiable information may include, but is not limited to:</p>
						<ul>
							<li>Email address</li>
							<li>First name and last name</li>
							<li>Phone number</li>
							<li>Address, State, Province, ZIP/Postal code, City</li>
						</ul>
						<p><strong>Usage Data</strong></p>
						<p>We may also collect information that your browser sends whenever you visit our Service or
							when you access the Service by or through a mobile device ("Usage Data"). This Usage Data
							may include information such as your computer's Internet Protocol address (e.g. IP address),
							browser type, browser version, the pages of our Service that you visit, the time and date of
							your visit, the time spent on those pages, unique device identifiers and other diagnostic
							data.</p>
						<h3>Use of Data</h3>
						<p>Sponsorrs uses the collected data for various purposes:</p>
						<ul>
							<li>To provide and maintain the Service</li>
							<li>To notify you about changes to our Service</li>
							<li>To allow you to participate in interactive features of our Service when you choose to do
								so</li>
							<li>To provide customer care and support</li>
							<li>To provide analysis or valuable information so that we can improve the Service</li>
							<li>To monitor the usage of the Service</li>
							<li>To detect, prevent and address technical issues</li>
						</ul>
						<h3>Transfer of Data</h3>
						<p>Your information, including Personal Data, may be transferred to - and maintained on -
							computers located outside of your state, province, country or other governmental
							jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
						<h3>Disclosure of Data</h3>
						<p>Sponsorrs may disclose your Personal Data in the good faith belief that such
							action is necessary to:</p>
						<ul>
							<li>Comply with a legal obligation</li>
							<li>Protect and defend the rights or property of Sponsorrs</li>
							<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
							<li>Protect the personal safety of users of the Service or the public</li>
							<li>Protect against legal liability</li>
						</ul>
						<h3>Security of Data</h3>
						<p>The security of your data is important to us, but remember that no method of transmission
							over the Internet or method of electronic storage is 100% secure. While we strive to use
							commercially acceptable means to protect your Personal Data, we cannot guarantee its
							absolute security.</p>
						<h3>Service Providers</h3>
						<p>We may employ third party companies and individuals to facilitate our Service ("Service
							Providers"), to provide the Service on our behalf, to perform Service-related services or to
							assist us in analyzing how our Service is used.</p>
						<p>These third parties have access to your Personal Data only to perform these tasks on our
							behalf and are obligated not to disclose or use it for any other purpose.</p>
						<h3>Links to Other Sites</h3>
						<p>Our Service may contain links to other sites that are not operated by us. If you click on a
							third-party link, you will be directed to that third party's site. We strongly advise you to
							review the Privacy Policy of every site you visit.</p>
						<p>We have no control over and assume no responsibility for the content, privacy policies or
							practices of any third-party sites or services.</p>
						<h3>Children's Privacy</h3>
						<p>Our Service does not address anyone under the age of 18 ("Children").</p>
						<p>We do not knowingly collect personally identifiable information from anyone under the age of
							18. If you are a parent or guardian and you are aware that your Children has provided us
							with Personal Data, please contact us. If we become aware that we have collected Personal
							Data from children without verification of parental consent, we take steps to remove that
							information from our servers.</p>
						<h3>Changes to This Data Privacy Policy</h3>
						<p>We may update our Data Privacy Policy from time to time. We will notify you of any changes by
							posting the new Data Privacy Policy on this page.</p>
						<p>We will let you know via email and/or a prominent notice on our Service, prior to the change
							becoming effective and update the "effective date" at the top of this Data Privacy Policy.
						</p>
						<p>You are advised to review this Data Privacy Policy periodically for any changes. Changes to
							this Data Privacy Policy are effective when they are posted on this page.</p>
						<h3>Contact Us</h3>
						<p>If you have any questions about this Data Privacy Policy, please contact us:</p>
						<ul>
							<li>By email: contact@sponsorrs.com</li>
							<li>By visiting this page on our website: https://www.sponsorrs.com</li>
						</ul>
					</div>
				</div> <!-- Row END -->
			</div>
		</section>
		<!-- ======================= Action box END -->
	</main>
	<!-- **************** MAIN CONTENT END **************** -->

	<!-- ======================= Footer START -->

	<?php include 'common_ui/footer.php'; ?>
	<!-- ====================== Footer END -->

	<!-- Back to top -->
	<div class="back-top"><i class="bi bi-arrow-up-short position-absolute top-50 start-50 translate-middle"></i></div>

	<!-- Bootstrap JS -->
	<script src="assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	<!-- Vendors -->
	<script src="assets/vendor/tiny-slider/tiny-slider.js"></script>
	<script src="assets/vendor/glightbox/js/glightbox.js"></script>

	<!-- Template Functions -->
	<script src="assets/js/functions.js"></script>

</body>

<!-- index-11.html  11 Feb 2023 14:24:49 GMT -->

</html>